# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '17.x'
    checkLatest: true
  displayName: 'Install Node.js'
    
- script: |
    cd React/library
    npm install
    npm run build
  displayName: 'Install modules and build the app'
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'React/library/build'
    skip_app_build: true
    azure_static_web_apps_api_token: '30288ccd79260ed9a8ed10b9d2aa301eed4eec7b0fd130616950ff38784f78a51-c74857d0-0afb-4014-b85c-a5ecccd5ba8200021925'