# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "17.x"
    displayName: "Install Node.js"

  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'React/library/'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'
      workingDir: 'React/library/'
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'XAM Core Subscription (c1c61fa4-a6ee-478f-a0a8-181a619b868a)'
      appType: 'webApp'
      WebAppName: 'Xam_Accelerator_React'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'