# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '17.x'
    checkLatest: true
  displayName: 'Install Node.js'
- task: CmdLine@2
  inputs:
    script: 'cd React/library'
    
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
